-- ============================================================================
-- 99_RESET.SQL — Reset Semiconductor Supply Chain Visibility to clean demo state
-- ============================================================================
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SUPPLIER_RISK_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.BOM_COST_ROLLUP REFRESH;
ALTER DYNAMIC TABLE CURATED.LEAD_TIME_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.SUPPLY_GRAPH REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SEMICONDUCTOR_SUPPLY_CHAIN.RAW.SUPPLIERS → 50
-- SELECT COUNT(*) FROM SEMICONDUCTOR_SUPPLY_CHAIN.RAW.BOM_ITEMS → 2000
-- SELECT COUNT(*) FROM SEMICONDUCTOR_SUPPLY_CHAIN.RAW.PURCHASE_ORDERS → 10000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
